### ISSUE TITLE
Gluu 3.1.8 QA - AWS custom attribute data record less than 2k

### ISSUE THREAD

**Issue by sahilIT2020** [GluuFederation/oxNotify#7]
Issue : User not getting push notification once appUserData reaches the limit of 2k 

There is a limit of 2k characters on AWS custom attribute data record which prevent from sending push notification to registered device.

Implement method to remove old items from appUserData based on FIFO

**Comment by yurem** [comment]
c79126149b73977f30cc2235e1f57716714f1876

**Comment by yurem** [comment]
@mzico can you test fix?

**Comment by yurem** [comment]
Fixed and tested
