### ISSUE TITLE
Getting 404 error while running on server .

### ISSUE THREAD

**Issue by rajlucky1996** [GluuFederation/oxNotify#8]
Hi I am trying to run the application , and i am facing 404 error while running on tomcat server .
It seems like it is missing some files .
please find the logs  below .

[error.log](https://github.com/GluuFederation/oxNotify/files/4700446/error.log)

**Comment by yuriyz** [comment]
If you look to log it clearly says
`Failed to load configuration from C:\Users\RajendraBaral\AppData\Local\JetBrains\IntelliJIdea2020.1\tomcat\Unnamed_oxnotify_3\conf\salt`. There no `salt` file.

Github is for bugs/features scheduled for fixes/development. For support questions please post ticket on support.gluu.org.
