### ISSUE TITLE
UserData in endpoint not serialized properly causes NPE

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxNotify#9]
According to [this](https://github.com/GluuFederation/oxNotify/blob/version_4.2.1/server/src/main/java/org/gluu/oxnotify/model/sns/CustomUserData.java) class, user data should be serialized with "client_id", "client_ip", "creation_date", "app_user_data" properties.

In AWS console there are users looking like:

![Clipboard - September 2, 2020 12_18 AM](https://user-images.githubusercontent.com/5444180/91897906-96d86100-ec60-11ea-9eb5-df46d4cb239c.png)

![Clipboard - September 2, 2020 12_46 AM](https://user-images.githubusercontent.com/5444180/91897924-9cce4200-ec60-11ea-91d4-283040117940.png)

(as if jackson annotations were ignored).

This caused problems as described in support ticket  8781, namely NPE [here](https://github.com/GluuFederation/oxNotify/blob/version_4.2.1/server/src/main/java/org/gluu/oxnotify/rest/NotifyRestServiceImpl.java#L178).

It seems  codehaus serialization was in place before so fasterxml annotations had no effect on CustomUserData.

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxNotify/commit/170b30d36b7b2535d6be9def1854ce8e0ae50c3f

**Comment by yurem** [comment]
Fixed
